version: "3.9"

services:

        selenium-chrome:
                image: selenium/standalone-chrome
                container_name: "dolarblue-selenium"
                restart: always
                environment:
                         - NODE_MAX_INSTANCE=20
                         - NODE_MAX_SESSION=20

        redis-db:
                image: redis
                container_name: "dolarblue-redis"
                restart: always

        dolarblue-api:
                image: dolarblue-api
                container_name: "dolarblue-api"
                restart: always
                ports:
                         - 80:80