version: "3.9"

services:

        redis-db:
                image: redis
                container_name: "dolarblue-redis"
                restart: always

        dolarblue-api:
                image: dolarblue-api
                container_name: "dolarblue-api"
                restart: always
                ports:
                         - 80:80
